version: "3.3"
services:
    homeassistant:
      container_name: homeassistant
      image: homeassistant/home-assistant:latest
      ports:
        - 8123:8123
      volumes:
        - $PWD/homeassistant:/config
