default_config:
discovery:

homeassistant:
  name: !secret NAME
  unit_system: metric
  time_zone: !secret TIME_ZONE
  latitude: !secret LATITUDE
  longitude: !secret LONGITUDE

frontend:
  themes: !include_dir_merge_named  themes


group: !include groups.yaml
automation: !include automations.yaml
automation dir: !include_dir_merge_list  automations
script: !include scripts.yaml
scene: !include scenes.yaml

